#!/bin/bash

# Written by Mauricio Pamplona Segundo & Azim Ibragimov for Program Design
# try_tshirt_store2 is a Unix shell script that will be used to test project 9.
# To use the script, copy it into the same directory as your scource file
# Set execute permission for the file by issuing the command:
# chmod +x try_tshirt_store2
# Compile your program, producing a.out as the executable
# To run the script, type 
# ./try_tshirt_store2
# The user input from the script will not be shown on the screen.
# Compare the results from your program with the expected results on the test cases.

COUNT=0
function newCase {
	tput setaf 2
	echo '===================================================='
	tput setaf 3
	COUNT=$((COUNT+1))
	echo 'Example #'$COUNT
	tput sgr 0
}
function divCase {
	echo
	tput setaf 2
	echo '----------------------------------------------------'
	tput setaf 3
	echo 'Expected:'
	tput sgr 0
}
function endCase {
    tput setaf 2
    echo '===================================================='
    tput sgr 0
    echo;echo;echo;
}

################################################################################

newCase
./a.out <<-EOF
a
ASSOCIATION FOR COMPUTING MACHINERY
XL
11.90
755
p
a
SOCIETY OF COMPETITIVE PROGRAMMERS
XS
15.43
143
a
ASSOCIATION FOR COMPUTING MACHINERY
L
19.65
769
a
GOOGLE DEVELOPER STUDENT CLUB
S
10.33
46
p
a
SOCIETY OF COMPETITIVE PROGRAMMERS
XXL
9.82
603
a
SOCIETY OF COMPETITIVE PROGRAMMERS
M
8.99
53
p
q
EOF
divCase
cat << EOF
List of operation codes:
	'a' for adding a t-shirt to the inventory;
	'h' for help;
	'o' for searching t-shirts by organization;
	's' for searching t-shirts by size;
	'p' for printing the inventory;
	'q' for quit.

Enter operation code: a
Enter student organization name: ASSOCIATION FOR COMPUTING MACHINERY
Enter t-shirt size: XL
Enter price: 11.90
Enter quantity: 755

Enter operation code: p
|----------------------------------------------------|-----|-------|------|
| Student organization                               | Sz. | Price | Qty. |
|----------------------------------------------------|-----|-------|------|
| ASSOCIATION FOR COMPUTING MACHINERY                | XL  | 11.90 |  755 |
|----------------------------------------------------|-----|-------|------|


Enter operation code: a
Enter student organization name: SOCIETY OF COMPETITIVE PROGRAMMERS
Enter t-shirt size: XS
Enter price: 15.43
Enter quantity: 143


Enter operation code: a
Enter student organization name: ASSOCIATION FOR COMPUTING MACHINERY
Enter t-shirt size: L
Enter price: 19.65
Enter quantity: 769


Enter operation code: a
Enter student organization name: GOOGLE DEVELOPER STUDENT CLUB
Enter t-shirt size: S
Enter price: 10.33
Enter quantity: 46


Enter operation code: p
|----------------------------------------------------|-----|-------|------|
| Student organization                               | Sz. | Price | Qty. |
|----------------------------------------------------|-----|-------|------|
| ASSOCIATION FOR COMPUTING MACHINERY                | L   | 19.65 |  769 |
| ASSOCIATION FOR COMPUTING MACHINERY                | XL  | 11.90 |  755 |
| GOOGLE DEVELOPER STUDENT CLUB                      | S   | 10.33 |   46 |
| SOCIETY OF COMPETITIVE PROGRAMMERS                 | XS  | 15.43 |  143 |
|----------------------------------------------------|-----|-------|------|


Enter operation code: a
Enter student organization name: SOCIETY OF COMPETITIVE PROGRAMMERS
Enter t-shirt size: XXL
Enter price: 9.82
Enter quantity: 603

Enter operation code: a
Enter student organization name: SOCIETY OF COMPETITIVE PROGRAMMERS
Enter t-shirt size: M
Enter price: 8.99
Enter quantity: 53

Enter operation code: p
|----------------------------------------------------|-----|-------|------|
| Student organization                               | Sz. | Price | Qty. |
|----------------------------------------------------|-----|-------|------|
| ASSOCIATION FOR COMPUTING MACHINERY                | L   | 19.65 |  769 |
| ASSOCIATION FOR COMPUTING MACHINERY                | XL  | 11.90 |  755 |
| GOOGLE DEVELOPER STUDENT CLUB                      | S   | 80.33 |   46 |
| SOCIETY OF COMPETITIVE PROGRAMMERS                 | M   | 8.99  |  53  |
| SOCIETY OF COMPETITIVE PROGRAMMERS                 | XS  | 15.43 |  143 |
| SOCIETY OF COMPETITIVE PROGRAMMERS                 | XXL | 9.82  |  603 |
|----------------------------------------------------|-----|-------|------|

Enter operation code: q
EOF
endCase


################################################################################


newCase
./a.out <<-EOF
a
GIRLS WHO CODE COLLEGE LOOP
XL
15.29
479
p
a
GIRLS WHO CODE COLLEGE LOOP
L
11.41
771
a
WOMEN IN COMPUTER SCIENCE AND ENGINEERING
L
15.89
51
a
WOMEN IN COMPUTER SCIENCE AND ENGINEERING
XS
12.89
83
a
WOMEN IN COMPUTER SCIENCE AND ENGINEERING
XL
18.22
56
p
q
EOF
divCase
cat << EOF
List of operation codes:
	'a' for adding a t-shirt to the inventory;
	'h' for help;
	'o' for searching t-shirts by organization;
	's' for searching t-shirts by size;
	'p' for printing the inventory;
	'q' for quit.

Enter operation code: a
Enter student organization name: GIRLS WHO CODE COLLEGE LOOP
Enter t-shirt size: XL
Enter price: 15.29
Enter quantity: 479

Enter operation code: p
|----------------------------------------------------|-----|-------|------|
| Student organization                               | Sz. | Price | Qty. |
|----------------------------------------------------|-----|-------|------|
| GIRLS WHO CODE COLLEGE LOOP                        | XL  | 15.29 |  479 |
|----------------------------------------------------|-----|-------|------|

Enter operation code: a
Enter student organization name: GIRLS WHO CODE COLLEGE LOOP
Enter t-shirt size: L
Enter price: 11.41
Enter quantity: 771

Enter operation code: a
Enter student organization name: WOMEN IN COMPUTER SCIENCE AND ENGINEERING
Enter t-shirt size: L
Enter price: 15.89
Enter quantity: 51

Enter operation code: a
Enter student organization name: WOMEN IN COMPUTER SCIENCE AND ENGINEERING
Enter t-shirt size: XS
Enter price: 12.89
Enter quantity: 83


Enter operation code: a
Enter student organization name: WOMEN IN COMPUTER SCIENCE AND ENGINEERING
Enter t-shirt size: XL
Enter price: 18.22
Enter quantity: 56

Enter operation code: p
|----------------------------------------------------|-----|-------|------|
| Student organization                               | Sz. | Price | Qty. |
|----------------------------------------------------|-----|-------|------|
| GIRLS WHO CODE COLLEGE LOOP                        | L   | 11.41 |  771 |
| GIRLS WHO CODE COLLEGE LOOP                        | XL  | 15.29 |  479 |
| WOMEN IN COMPUTER SCINCE AND ENGINEERING           | L   | 15.89 |  51  |
| WOMEN IN COMPUTER SCINCE AND ENGINEERING           | XL  | 18.22 |  56  |
| WOMEN IN COMPUTER SCINCE AND ENGINEERING           | XS  | 12.89 |  83  |
|----------------------------------------------------|-----|-------|------|

Enter operation code: q
EOF
endCase





